### ISSUE TITLE
"Sign in" button does not work in Safari

### ISSUE THREAD

**Issue by warpech** [Starcounter/starcounter.io#79] opened 2015-11-04 12:44 UTC
In the App Hub, the "Sign in" button does not work in Safari.

Tested yesterday on Kristoffer's Mac

**Comment by miyconst** [comment] 2015-11-05 11:33
The issue was between `Object.observe` shim and `json-patch` fighting each other because of "specific" understanding of `"use strict"` by Safari.

**Comment by miyconst** [comment] 2015-11-05 11:34
The issue is solved by removing `Object.observe` usage from `json-patch`. I will update `starcounter.io` with the latest Starcounter tomorrow and close this issue.

**Closed** 2015-11-06 14:54 UTC
